"""Add cart and order tables

Revision ID: 561c61a0e3bd
Revises: 261d7611c322
Create Date: 2025-10-28 07:51:26.591073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561c61a0e3bd'
down_revision: Union[str, None] = '261d7611c322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('total_items >= 0', name='check_non_negative_total_items'),
    sa.CheckConstraint('total_price >= 0', name='check_non_negative_total_price'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_cart_user', 'carts', ['user_id'], unique=False)
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity > 0', name='check_positive_cart_quantity'),
    sa.CheckConstraint('total_price >= 0', name='check_non_negative_cart_total_price'),
    sa.CheckConstraint('unit_price >= 0', name='check_non_negative_cart_unit_price'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cart_item_cart', 'cart_items', ['cart_id'], unique=False)
    op.create_index('idx_cart_item_product', 'cart_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.add_column('order_items', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('order_items', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('orders', sa.Column('billing_address_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('orders', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_foreign_key(None, 'orders', 'addresses', ['billing_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'currency')
    op.drop_column('orders', 'billing_address_id')
    op.alter_column('order_items', 'order_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('order_items', 'id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('order_items', 'updated_at')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_index('idx_cart_item_product', table_name='cart_items')
    op.drop_index('idx_cart_item_cart', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_index('idx_cart_user', table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###
